"""add message_context json column to messages

Revision ID: 07a6ff0a3fbb
Revises: 7d6125b5a2ca
Create Date: 2026-03-30 17:58:29.497941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a6ff0a3fbb'
down_revision: Union[str, Sequence[str], None] = '7d6125b5a2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message_context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_context')
    # ### end Alembic commands ###
