"""add_resumed_from_conversation_id_to_conversations

Revision ID: a1953ca7333f
Revises: 07a6ff0a3fbb
Create Date: 2026-04-01 01:03:37.009454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1953ca7333f'
down_revision: Union[str, Sequence[str], None] = '07a6ff0a3fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('resumed_from_conversation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'conversations', ['resumed_from_conversation_id'], ['conversation_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'resumed_from_conversation_id')
    # ### end Alembic commands ###
